[package]
name = "sqlite-replicated"
version.workspace = true
edition.workspace = true
publish = false

[features]
testing = ["kuberic-runtime/testing", "dep:tempfile"]

[[bin]]
name = "sqlite-replicated"
path = "src/main.rs"

[dependencies]
kuberic-runtime = { workspace = true, features = ["host"] }
libsqlite3-sys = { version = "0.38", features = ["bundled"] }
tempfile = { version = "3", optional = true }
async-trait.workspace = true
futures.workspace = true
tokio.workspace = true
tokio-util.workspace = true
tokio-stream.workspace = true
tracing.workspace = true
tracing-subscriber.workspace = true
bytes.workspace = true
tonic.workspace = true
prost.workspace = true
tonic-prost.workspace = true
serde = { workspace = true, features = ["derive"] }
serde_json.workspace = true
clap.workspace = true
rusqlite = { workspace = true, features = ["hooks"] }
crc32fast.workspace = true

[dev-dependencies]
sqlite-replicated = { path = ".", features = ["testing"] }
tempfile = "3"

[build-dependencies]
tonic-prost-build.workspace = true
