[package]
name = "kuberic-runtime"
version.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true
rust-version.workspace = true
description = "Independent level-triggered application and replication runtime for Kuberic"
readme = "README.md"

[dependencies]
async-trait.workspace = true
bytes.workspace = true
futures.workspace = true
kuberic-protocol = { path = "../kuberic-protocol" }
kuberic-wire = { path = "../kuberic-wire" }
thiserror.workspace = true
tokio.workspace = true
uuid = { workspace = true, features = ["v4"] }
