---
apiVersion: kubelicate.io/v1
kind: KubelicateSet
metadata:
  name: kvstore
  namespace: xedio
spec:
  replicas: 3
  image: localhost/kvstore:latest
  port: 8080
  controlPort: 9090
  dataPort: 9091
  storage: "256Mi"
  failoverDelay: 5
